[tool.poetry]
name = "documentation"
version = "1.0.0"
description = "Autogenerate postgres extension documentation from sql files"
authors = ["Zacharias Knudsen <z@chari.as>"]

[tool.poetry.dependencies]
python = "^3.10"
lark-parser = "^0.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
